### ISSUE TITLE
Developer options webview

### ISSUE THREAD

**Issue by dviree** [alexa-v2/bromite-systemless#1]
Hi it seems like my phone can't change the webview from chrome to bromite
![Screenshot_20190531-140224](https://user-images.githubusercontent.com/33899343/58701856-d30d7980-83ac-11e9-95c1-9dad2076668a.png)

**Comment by alexa-v2** [comment]
Your ROM must support using "com.android.webview" as the webview and not have a pinned signature for the app

**Comment by alexa-v2** [comment]
To see if it does:
From a terminal such as termux:
- cp  /system/framework/framework-res.apk ~
- aapt d xmltree framework-res.apk res/xml/config_webview_packages.xml

The output should contain. "com.android.webview" and not contain a "C:" with a bunch of characters under it

**Comment by dviree** [comment]
Shit, I got the official rom from Google. So it's impossible to use the bromite webview then

**Comment by alexa-v2** [comment]
Most likel,  but also depends on OEM

I pushed an update that has a small chance of fixing your problem but I wouldn't hold my breath

**Comment by Dark-Cod3r** [comment]
Same issue here... No bromite option in developer option..
Using miui 10 (android 9.0)

**Comment by alexa-v2** [comment]
Closed #1
