### ISSUE TITLE
Error messages on testing the installation

### ISSUE THREAD

**Issue by kgursu** [alexa-v2/bromite-systemless#2]
Hi.

Here is that issue I posted on XDA: https://forum.xda-developers.com/android/apps-games/app-bromite-chromium-plus-adblocking-t3687258/post79643303
Is there a solution? Following posts will give you the whole picture.
We need a more comprehensive step-by-step guide to accomplish the task to finilaze the installation. A Telegram group might be able to support that purpose.

Thanks...

**Comment by alexa-v2** [comment]
Aapt should not be ran as root, since its a termux package, first off. Thats the first error in the thread
________________________________

**Comment by kgursu** [comment]
Ok. The result is as follows:![](https://i.imgur.com/BzustHE.jpg)

**Comment by alexa-v2** [comment]
You should be able to use it yes
you may have to disable chrome first though

**Comment by alexa-v2** [comment]
Considering the issue resolved, closing

**Comment by alexa-v2** [comment]
By the way, our new support group: https://t.me/inlmagisk
