### ISSUE TITLE
Problems with OkCupid after installation/update

### ISSUE THREAD

**Issue by Enkidu70** [alexa-v2/bromite-systemless#3]
I have installed Bromite Systemless Webview on my Oneplus 3T Resurrection Remix 7.0.2 (Android 9, based on LineageOS).

Every time I install/update this module, OkCupid (https://play.google.com/store/apps/details?id=com.okcupid.okcupid) tells me no Webview available and refuses to work.

After installing Android System Webview from Playstore additionally to this module, OkCupid is working again.
(Also it is very strange, because installation of Webview from Playstore needs really really long...)

So there might be something missing in installation of this module because OkCupid seems not to accept/dedect it...

But it seems that Bromite is not working together with my rom at all. Because I do not see Bromite in selection of Webview implementation. Just Chrome (like in the picture of issue #1)...

Could you please check this problem?
Tnx in advane.

![Screenshot_20190609-203030_OkCupid~01](https://user-images.githubusercontent.com/1456895/59567473-84c7ce00-906e-11e9-9a49-7569ae64981a.png)

**Comment by alexa-v2** [comment]
Obviously a app issue

It specifically asks for Android System Webview, a Google app itself. More than likely checks for "com.google.android.webview" which causes issues for some users with bromite so is debloated by my module

Please note if an app requires Google webview there is nothing I can do about it. Use the app webview test (https://play.google.com/store/apps/details?id=com.snc.test.webview2) to test the webview and go to bromite.org/detect and with just bromite you should get 5/9

Especially if other apps work (like webview test) don't complain its an app issue

Closing as I can't change other apps

**Comment by Enkidu70** [comment]
Well... But my issue is, after updating Bromite Magisk module, Android System Webview is gone!

Why?

Can't you link it in filesystem or something llike that?
If you can delete it, you also could not delete it! ;)
